# fly.toml file generated for fullstackopen-kaif-pokemon on 2023-03-19T11:43:33+02:00

app = "fullstackopen-kaif-pokemon"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "8080"

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"
  
[experimental]
  auto_rollback = true


[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    interval = "20s"
    grace_period = "10s"
    method = "get"
    path = "/health"
    protocol = "http"
    restart_limit = 0
    timeout = 3000
    tls_skip_verify = true
  
  [[services.script_checks]]
    command = "/app/health_check.sh"
    grace_period = "10s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"